const mongoose = require("mongoose");
const Schema = mongoose.Schema({
  ic: String,
  rank: String,
  name: String,
  cdaAcNo: String,
  unit: String,
  appointment: String,
  mobile: Number,
  reportingDate: String,
  dob: String,
  commissionDate: String,
  accnDate: String,
  marriageDate: String,
  isMarried: Boolean,
  isDependent: Boolean,
  wifeName: String,
  children1: String,
  children2: String,
  children1Age: String,
  children2Age: String,
  marriageDate: String,
  dependent1: String,
  dependent2: String,
  dependent3: String,
  dependent4: String,
  dependent1Relation: String,
  dependent2Relation: String,
  dependent3Relation: String,
  dependent4Relation: String,
  years: String,
  months: String,
  days: String,
  unitArea1: String,
  unitArea2: String,
  from1: String,
  from2: String,
  to1: String,
  to2: String,
  occupiedAccom: String,
  familyStay: String,
  familyStay2: String,
  vehMake: String,
  vehRegistration: String,
  preference1: String,
  preference2: String,
  preference3: String,
  agreed: String,

  created_at: {
    type: Date,
    default: Date.now(),
  },
});

const UserSchema = mongoose.model("User", Schema);

module.exports = UserSchema;
